In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
from sklearn import preprocessing
%matplotlib inline

In [9]:
df_train = pd.read_csv("https://raw.githubusercontent.com/Shreyas3108/Titanic-EDA-and-Survival-prediction/master/train.csv", sep = ",")
df_test  =pd.read_csv("https://raw.githubusercontent.com/Shreyas3108/Titanic-EDA-and-Survival-prediction/master/test.csv", sep=",")
df =pd.concat([df_train,df_test])

C:\Users\Dell\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  This is separate from the ipykernel package so we can avoid doing imports until


In [10]:
df.head()

Age Cabin Embarked     Fare  \
0  22.0   NaN        S   7.2500   
1  38.0   C85        C  71.2833   
2  26.0   NaN        S   7.9250   
3  35.0  C123        S  53.1000   
4  35.0   NaN        S   8.0500   

                                                Name  Parch  PassengerId  \
0                            Braund, Mr. Owen Harris      0            1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...      0            2   
2                             Heikkinen, Miss. Laina      0            3   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)      0            4   
4                           Allen, Mr. William Henry      0            5   

   Pclass     Sex  SibSp  Survived            Ticket  
0       3    male      1       0.0         A/5 21171  
1       1  female      1       1.0          PC 17599  
2       3  female      0       1.0  STON/O2. 3101282  
3       1  female      1       1.0            113803  
4       3    male      0       0.0            373450

In [14]:
df1= df.dropna(subset=["Survived"])

In [16]:
df1.head()

Age Cabin Embarked     Fare  \
0  22.0   NaN        S   7.2500   
1  38.0   C85        C  71.2833   
2  26.0   NaN        S   7.9250   
3  35.0  C123        S  53.1000   
4  35.0   NaN        S   8.0500   

                                                Name  Parch  PassengerId  \
0                            Braund, Mr. Owen Harris      0            1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...      0            2   
2                             Heikkinen, Miss. Laina      0            3   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)      0            4   
4                           Allen, Mr. William Henry      0            5   

   Pclass     Sex  SibSp  Survived            Ticket  
0       3    male      1       0.0         A/5 21171  
1       1  female      1       1.0          PC 17599  
2       3  female      0       1.0  STON/O2. 3101282  
3       1  female      1       1.0            113803  
4       3    male      0       0.0            373450

In [17]:
df1.insert(loc =2,column = "Has_cabin",value=df1["Cabin"].notna())

In [18]:
import re
df1["Title"]=df1.Name.apply(lambda x : re.search('([A-Z][a-z]+)\.',x).group(1))
df1["Title"].unique()

C:\Users\Dell\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


array(['Mr', 'Mrs', 'Miss', 'Master', 'Don', 'Rev', 'Dr', 'Mme', 'Ms',
       'Major', 'Lady', 'Sir', 'Mlle', 'Col', 'Capt', 'Countess',
       'Jonkheer'], dtype=object)

In [19]:
list = ["Don","Rev","Dr","Mme","Ms","Major","Lady","Sir","Mlle","Col","Capt","Countess","Jonkheer"]
df1["Title"] = df1["Title"].replace(list,"Special")

C:\Users\Dell\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


In [20]:
df1["Title"].unique()

array(['Mr', 'Mrs', 'Miss', 'Master', 'Special'], dtype=object)

In [21]:
df1 =df1.fillna(df1.mean())

In [22]:
df2 = df1["Cabin"].fillna("B96")
df3 = df1["Embarked"].fillna("S")
df1 = df1.drop(["Cabin","Embarked"],axis =1)

In [23]:
df1.isnull().sum()

Age            0
Has_cabin      0
Fare           0
Name           0
Parch          0
PassengerId    0
Pclass         0
Sex            0
SibSp          0
Survived       0
Ticket         0
Title          0
dtype: int64

In [24]:
df1.insert(loc =1 ,column = "Cabin",value = df2)
df1.insert(loc =1 ,column = "Embarked",value = df3)

In [25]:
df1["Categorical_age"] = pd.qcut(df1.Age,q= 4,labels = False)
df1["Categorical_fare"] =  pd.qcut(df1.Fare,q=4,labels =False)

In [26]:
df1.head()

Age Embarked Cabin  Has_cabin     Fare  \
0  22.0        S   B96      False   7.2500   
1  38.0        C   C85       True  71.2833   
2  26.0        S   B96      False   7.9250   
3  35.0        S  C123       True  53.1000   
4  35.0        S   B96      False   8.0500   

                                                Name  Parch  PassengerId  \
0                            Braund, Mr. Owen Harris      0            1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...      0            2   
2                             Heikkinen, Miss. Laina      0            3   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)      0            4   
4                           Allen, Mr. William Henry      0            5   

   Pclass     Sex  SibSp  Survived            Ticket Title  Categorical_age  \
0       3    male      1       0.0         A/5 21171    Mr                0   
1       1  female      1       1.0          PC 17599   Mrs                3   
2       3  female      0       1.0  STON/O2. 3101282  Miss                1   
3       1  female      1       1.0            113803   Mrs                2   
4       3    male      0       0.0            373450    Mr                2   

   Categorical_fare  
0                 0  
1                 3  
2                 1  
3                 3  
4                 1

In [27]:
df1=  df1.drop(["Cabin", "Name", "PassengerId", "Ticket", "Age", "Fare", "SibSp", "Parch" ],axis = 1)

In [28]:
df1 = pd.get_dummies(df1)

In [29]:
X = df1.drop(["Survived"],axis = 1)
y = df1["Survived"]

In [36]:
from sklearn import model_selection 

In [37]:
kfold = model_selection.KFold(n_splits=10,random_state=7)

In [38]:
from sklearn.linear_model import LogisticRegression

In [39]:
reg = LogisticRegression()

In [45]:
res = model_selection.cross_val_score(reg,X,y,cv = kfold,scoring="accuracy")

In [46]:
res

array([0.8       , 0.78651685, 0.78651685, 0.85393258, 0.79775281,
       0.80898876, 0.79775281, 0.7752809 , 0.87640449, 0.83146067])

In [48]:
res1 = model_selection.cross_val_score(reg,X,y,cv = kfold,scoring="neg_log_loss")

In [49]:
res1

array([-0.46446036, -0.44957261, -0.47967042, -0.4528883 , -0.44788133,
       -0.43041582, -0.47262611, -0.47149449, -0.33986549, -0.39437856])

In [50]:
from sklearn.metrics import confusion_matrix

In [51]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3)

In [52]:
reg.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [53]:
reg.coef_

array([[ 0.80599856, -0.75919734, -0.12916672, -0.03857851,  0.50812408,
         0.33509732,  0.12898211,  1.33140923, -0.35920572,  1.46206722,
         0.17713981, -0.8065342 ,  0.53940128, -0.3998706 ]])

In [55]:
reg.intercept_

array([0.97220351])

In [56]:
res2 = reg.predict(X_test)

In [58]:
print(confusion_matrix(y_test,res2))

[[145  25]
 [ 22  76]]
