In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris

In [2]:
data = load_iris()

In [3]:
X = data.data

In [4]:
y = data.target

### Bagging

from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import RandomForestClassifier

In [6]:
cart = RandomForestClassifier()

In [7]:
model = BaggingClassifier(base_estimator= cart,n_estimators=100,n_jobs=2,random_state=42)

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size =0.3)

In [10]:
model.fit(X_train,Y_train)

BaggingClassifier(base_estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False),
         bootstrap=True, bootstrap_features=False, max_features=1.0,
         max_samples=1.0, n_estimators=100, n_jobs=2, oob_score=False,
         random_state=42, verbose=0, warm_start=False)

In [11]:
pre = model.predict(X_test)

In [14]:
from  sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [15]:
print(classification_report(pre,Y_test))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        14
          1       0.94      0.94      0.94        18
          2       0.92      0.92      0.92        13

avg / total       0.96      0.96      0.96        45



In [16]:
print(confusion_matrix(pre,Y_test))

[[14  0  0]
 [ 0 17  1]
 [ 0  1 12]]


In [17]:
print(accuracy_score(pre,Y_test))

0.9555555555555556


### Boosting

#### AdaBoost

In [18]:
from sklearn.ensemble import AdaBoostClassifier

In [19]:
model2 = AdaBoostClassifier(base_estimator=cart,n_estimators=100,random_state=42)

In [20]:
model2.fit(X_train,Y_train)

AdaBoostClassifier(algorithm='SAMME.R',
          base_estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False),
          learning_rate=1.0, n_estimators=100, random_state=42)

In [21]:
pre2 = model2.predict(X_test)

In [22]:
print(classification_report(pre,Y_test))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        14
          1       0.94      0.94      0.94        18
          2       0.92      0.92      0.92        13

avg / total       0.96      0.96      0.96        45



In [23]:
print(confusion_matrix(pre,Y_test))

[[14  0  0]
 [ 0 17  1]
 [ 0  1 12]]


In [24]:
print(accuracy_score(pre,Y_test))

0.9555555555555556


#### Gradient Boosting Classifier

In [25]:
from sklearn.ensemble import GradientBoostingClassifier

In [30]:
model3 = GradientBoostingClassifier(n_estimators=100,random_state=7)

In [31]:
model3.fit(X_train,Y_train)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=100,
              presort='auto', random_state=7, subsample=1.0, verbose=0,
              warm_start=False)

In [32]:
pre3 = model3.predict(X_test)

In [33]:
print(classification_report(pre3,Y_test))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        14
          1       0.94      0.89      0.92        19
          2       0.85      0.92      0.88        12

avg / total       0.94      0.93      0.93        45



In [34]:
print(confusion_matrix(pre3,Y_test))

[[14  0  0]
 [ 0 17  2]
 [ 0  1 11]]


In [35]:
print(accuracy_score(pre3,Y_test))

0.9333333333333333


### Voting

In [36]:
from sklearn.ensemble import VotingClassifier

In [41]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.cluster import KMeans
from sklearn.naive_bayes import GaussianNB

In [46]:
estimater = []
model4 = LogisticRegression()
estimater.append(("linear",model4))
model5 = KMeans()
estimater.append(("KMeans",model5))
model6 = SVC(kernel="rbf")
estimater.append(("SVC",model6))
model7 = GaussianNB()
estimater.append(("Gaussian",model7))


In [47]:
classify = VotingClassifier(estimater)

In [48]:
classify.fit(X_train,Y_train)

VotingClassifier(estimators=[('linear', LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)), ('KMeans',...dom_state=None, shrinking=True,
  tol=0.001, verbose=False)), ('Gaussian', GaussianNB(priors=None))],
         flatten_transform=None, n_jobs=1, voting='hard', weights=None)

In [49]:
pre4 = classify.predict(X_test)

In [50]:
print(classification_report(pre4,Y_test))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        14
          1       1.00      1.00      1.00        18
          2       1.00      1.00      1.00        13

avg / total       1.00      1.00      1.00        45



In [51]:
print(confusion_matrix(pre4,Y_test))

[[14  0  0]
 [ 0 18  0]
 [ 0  0 13]]


In [53]:
print(accuracy_score(pre4,Y_test)*100)

100.0
