In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv("bill_authentication.csv")

In [4]:
data.head()

Variance  Skewness  Curtosis  Entropy  Class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

In [6]:
X= data.drop(columns=["Class"],axis =1)
Y= data["Class"]

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size =0.2)

### Decision Tree

In [8]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(X_train,Y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [9]:
pre = model.predict(X_test)

In [10]:
model.score(X_test,Y_test)

0.9818181818181818

In [11]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [13]:
print(classification_report(pre,Y_test))

             precision    recall  f1-score   support

          0       0.99      0.97      0.98       147
          1       0.97      0.99      0.98       128

avg / total       0.98      0.98      0.98       275



In [14]:
print(confusion_matrix(pre,Y_test))

[[143   4]
 [  1 127]]


In [15]:
print(accuracy_score(pre,Y_test))

0.9818181818181818


### Random Forest

In [16]:
from sklearn.ensemble import RandomForestClassifier

In [17]:
model2 = RandomForestClassifier(n_estimators=100,n_jobs=2,random_state=0)

In [18]:
model2.fit(X_train,Y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=2,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [19]:
pre2= model2.predict(X_test)

In [20]:
print(classification_report(pre2,Y_test))

             precision    recall  f1-score   support

          0       1.00      0.99      0.99       146
          1       0.98      1.00      0.99       129

avg / total       0.99      0.99      0.99       275



In [21]:
print(confusion_matrix(pre2,Y_test))

[[144   2]
 [  0 129]]


In [22]:
print(accuracy_score(pre2,Y_test))

0.9927272727272727


In [23]:
model2.predict_proba(X_test)

array([[0.  , 1.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.03, 0.97],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [0.01, 0.99],
       [0.01, 0.99],
       [0.  , 1.  ],
       [0.04, 0.96],
       [0.99, 0.01],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [0.02, 0.98],
       [1.  , 0.  ],
       [0.01, 0.99],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [0.07, 0.93],
       [0.  , 1.  ],
       [0.  , 1.  ],
       [0.02, 0.98],
       [1.  , 0.  ],
       [0.99, 0.01],
       [0.01, 0.99],
       [0.01, 0.99],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [0.03, 0.97],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.61, 0.39],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.04, 0.96],
       [0.  , 1.  ],
       [0.96, 0.04],
       [1.  ,