In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [5]:
from sklearn.datasets import load_iris

In [8]:
iris = load_iris()
data = iris.data
target = iris.target

In [10]:
data = pd.DataFrame(data)

In [11]:
data.head()

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

In [13]:
from sklearn.svm import SVC

In [16]:
from sklearn.model_selection import train_test_split
data_train,data_test,target_train,target_test = train_test_split(data,target,test_size = 0.3)

In [17]:
model = SVC(kernel = "linear")

In [18]:
model.fit(data_train,target_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [24]:
pred = model.predict(data_test)

In [21]:
from sklearn.metrics import confusion_matrix,accuracy_score


In [25]:
print(confusion_matrix(pred,target_test))

[[18  0  0]
 [ 0 11  0]
 [ 0  1 15]]


In [26]:
print(accuracy_score(pred,target_test))

0.9777777777777777


In [27]:
model1 = SVC(kernel="poly",degree=8)

In [28]:
model1.fit(data_train,target_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=8, gamma='auto', kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [29]:
pred1 = model1.predict(data_test)

In [30]:
print(confusion_matrix(pred1,target_test))
print(accuracy_score(pred1,target_test))

[[18  0  0]
 [ 0 11  0]
 [ 0  1 15]]
0.9777777777777777


In [31]:
model2 = SVC(kernel = "sigmoid")

In [32]:
model2.fit(data_train,target_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='sigmoid',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [33]:
pred2 = model2.predict(data_test)

In [34]:
print(accuracy_score(pred2,target_test))
print(confusion_matrix(pred2,target_test))

0.26666666666666666
[[ 0  0  0]
 [18 12 15]
 [ 0  0  0]]


In [35]:
model3 = SVC(kernel= 'rbf')

In [36]:
model3.fit(data_train,target_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [37]:
pred3 = model3.predict(data_test)

In [39]:
print(confusion_matrix(pred3,target_test))
print(accuracy_score(pred3,target_test))

[[18  0  0]
 [ 0 12  2]
 [ 0  0 13]]
0.9555555555555556
